# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Daily Github-Trending

on:
   push:
   schedule:
    - cron: "0 2 */7 * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Scraper
      env:
        username: ${{ secrets.MAILUSERNAME }}
        password: ${{ secrets.MAILPASSWORD }}
        appId: 3920410
      run: |
        python scraper.py

    # Runs a set of commands using the runners shell
    - name: push to origin master
      run: |
        echo start push
        git config --global user.name "biao.chen"
        git config --global user.email "biao.chenit@qq.com"
        
        git add -A
        git commit -m $(date '+%Y-%m-%d')
        git push
      
